### ISSUE TITLE
Functions to implement

### ISSUE THREAD

**Issue by emeyers** [emeyers/Brain-Observatory-Toolbox#1]
**Functions to get information about the data:**

These functions could either get the information via JSON files on the web, or we could just download the data and it pulls the data from a static file. 
 
- get_all_targeted_structures (?)
- get_all_cre_lines
- get_all_reporter_lines
- get_all_imaging_depths
- get_all_session_types
- get_all_stimuli
- get_experiment_containers(self, file_name=None,
                                  ids=None,
                                  targeted_structures=None,
                                  imaging_depths=None,
                                  cre_lines=None,
                                  transgenic_lines=None,
                                  include_failed=False,
                                  simple=True)

**Functions to get the data:**

Takes an experimental ID and download the NWB file: 

- get_ophys_experiment_data(ophys_experiment_id, save_directory_name)

**Functions to convert the data to raster format:**

Perhaps the get_ophys_experiment_data could do this directly, or we could have functions with names like:

- create_raster_data(nwb_file_name, experiment_type)

where experiment_type is "static_grating", "drifting_grating", "sparse_noise", etc.

**Comment by Xinzhu-Fang** [comment]
generally implemented all, has fewer filters to select desired containers or sessions than allensdk does
