### ISSUE TITLE
Restore Experiment object creation/construction

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#101]

**Comment by vijayiyer05** [comment]
Hi @DylanMuir, not sure if this comment in the linked pull request reached you: 
https://github.com/emeyers/Brain-Observatory-Toolbox/pull/126#issuecomment-882074110

Short version: I ran into a couple of issues. One I could fix right away, the other I couldn't.

**Comment by vijayiyer05** [comment]
@DylanMuir : can you see a smooth path to making the "linked items" connection between experiment and session items? 

In other words: each experiment's `.session` property should return a 3-row table of the sessions associated to that experiment.

**Comment by DylanMuir** [comment]
@vijayiyer05 This issue and merge request #126 is ready to review and merge. I believe the linked items query regarding `.sessions` property is also satisfied.

**Comment by DylanMuir** [comment]
@vijayiyer05 Please merge when you're happy with it.
