### ISSUE TITLE
Physiology Tutorial Updates

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#102]
The tutorials (one per dataset type) are meant to be longer-form and more didactic (with respect to both the datasets and the toolbox).

Overall the goal of this Issue is to evolve the organization and content of the tutorial set to provide full and navigable coverage of the BOT functionalities in a digestible way. 

Maintaining here an active list of some specific ideas: 
- [ ] Explain & show distinguishing examples for each of the two item object creation pathways: by ID and by table. The former is well-suited for sortrows operations while the latter allows one-line combinations of filtering & indexing. 
- [ ] Replace usage of bsxfun with implicit array expansion where possible 
- [ ] Illustrate the alignment of LFP probe data to channels (note: this may uncover need for additional utility functionality)
- [ ] Further teach users how to navigate item hierarchy, eg. via linked item IDs

**Comment by vijayiyer05** [comment]
@kzhou085, I took a look at the updated `EphysTutorial.mlx`. It's good to see we're conserving the content from `EphysDemo.mlx` to start thinking about where things go. 

I have two suggestions:
* The visual stimulus section is mostly self-contained towards the end, so I'm inclined to splice that out and to start a new `BehaviorTutorial.mlx` as the starting point for #110. 
* Add a table of contents near the top so we can take a look over the whole remaining structure and think about the overall organization

**Comment by kzhou085** [comment]
I've completed a draft of the updated ephys tutorial and placed it under the frontend branch for review.

**Comment by vijayiyer05** [comment]
@kzhou085: great to see the tutorial shaping up now into a clear structure/story!

I've done a first review and gathered up some initial suggestions: [EphysTutorial.pdf](https://github.com/emeyers/Brain-Observatory-Toolbox/files/6874435/EphysTutorial.pdf). 

Suggest we find a [short time](https://calendly.com/vijayi/office-hours) to meet this week and discuss this one in real-time.

**Comment by vijayiyer05** [comment]
One aspect covered in the suggestions and in the tasks above are the two pathways for object creation: supplying an ID array vs supplying a table object. 

I was discussing this with @emeyers last week, in relation to #116.

Here's my current thinking: 

To my thinking, table semantics is a must-have, since the only pathway to finding objects to create is via manifest tables. Also table semantics allow filtering (via table indexing) and object creation to be combined in one line which I think is quite nice. 

A question mark for me is whether ID array semantics are actually necessary or desirable for any use cases? (once multi-row tables can be supplied to object constructors, i.e. completion of #108). 

There's was a note above that ID arrays enable easier use of `sortrows`. But I'm no longer sure what that meant since I believe `sortrows` should work with tables too.  

Probably the best way for now is to try explaining both in the `EphysTutorial` as in the suggestions above. This process of explanation should help stimulate some thought about the "why?" for both cases. If the only reason for ID is to support arrays (as in #116) then we may want to remove this pathway once #108 is completed.

**Comment by kzhou085** [comment]
An updated version of the ephys tutorial is now awaiting review under the frontend branch.

**Comment by emeyers** [comment]
I will look over the ephys tutorial, the ephys quickstart and the ephys
demo and give you feedback on those.  I plan to look at these as pdf and
will send the pdfs with comments on them.

Are there any other tutorials I should look at (the behavioral tutorial or
perhaps we should wait until the bug in BOT has been fixed)?
