### ISSUE TITLE
Handle Item object property warnings

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#103]
For instance: common warnings for channel_structure_intervals

**Comment by DylanMuir** [comment]
HI @vijayiyer05, which warnings do you envisage here?

**Comment by vijayiyer05** [comment]
Hi @DylanMuir, the issue was framed as plural because it may make sense to have a general solution to deal with warnings on any property accesss. The precipitating issue is the `channel_structure_intervals` property mentioned above: it often returns warnings. This results in a messy item object display as shown below. 

Originally I was wondering if we should capture warnings into some property, i.e. a structure of "warning states". But that seems too complex. 

Now I'm thinking the best solution would be to catch warnings on property access and then to "rethrow" them at the end of the item object display with some reformatting to hide the stack:, e.g. "Warning (channel_structure_intervals): Structure boundaries were calculated across channels from multiple probes".  The phrases should all be past tense, and I think that works for both the whole item display and direct property access use cases.

Alternatively, since this is the only one known warning scenario, we might think about other ways to handle this specific property in the multi probe case. For instance, should this be turned into a table array, one per probe? 

Thoughts welcomed!

![image](https://user-images.githubusercontent.com/23032671/133930256-ac2508b4-bf69-45e7-9b9c-288b02a438f4.png)

**Comment by DylanMuir** [comment]
Implemented in branch `iss103`

**Comment by vijayiyer05** [comment]
Great! Slight improvement for future: include the property name impacted by the deferred warning line.
