### ISSUE TITLE
Convert stimulus_presentations & stimulus_epochs to timetables

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#106]
In tandem, it likely makes sense to convert stop_time into duration and to represent as a duration array

**Comment by DylanMuir** [comment]
branch `iss_106` contains updates to fixed some bugs regarding extracting stimulus tables, and include start and end times as durations.

@vijayiyer05 Since there are both `start` and `end` times for a given stimulus, I wasn't sure whether a `timetable` was appropriate. What is your opinion?

**Comment by vijayiyer05** [comment]
@DylanMuir, I believe original thinking was to use `start` time as the `timetable` time index and then to convert the `end` time column into a computed `duration` array that appears as one of the table columns. In that way, there's only one time index. Make sense?

**Comment by DylanMuir** [comment]
@vijayiyer05 Please merge when you're happy

**Comment by vijayiyer05** [comment]
@DylanMuir  The `stimulus_epoch_table` property looks good to me for ophys sessions. I'm glad you spotted this opportunity in the same vein. This issue was aimed at the corresponding ephys properties: `stimulus_presentations` and `stimulus_conditions`. Can you see a path to do similar for those?

**Comment by vijayiyer05** [comment]
Reopening this issue as it appears `stimulus_presentations` remains a `table` versus a `timetable` for `EphysSession` objects.

Correcting issue title to indicate intended conversion applies to `stimulus_presentations`  & `stimulus_epochs` (not `stimulus_conditions`).

**Comment by DylanMuir** [comment]
Merged into `master`
