### ISSUE TITLE
Improve Item object array handling

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#108]
Various improvements seem needed for Item object arrays, including at least:
- [x] Support item object array creation by multi-row item info table 
- [x] Item object display handling for the object array case (likely implement [displayNonscalarObject](https://www.mathworks.com/help/matlab/ref/matlab.mixin.customdisplay.displaynonscalarobject.html))

**Comment by vijayiyer05** [comment]
@DylanMuir: this could be a good near-term priority (particularly task 1) as it relates to ongoing work on #116 this summer. 

One thing I was discussing with @emeyers are the two pathways for object creation: supplying an ID array vs supplying a table object. 

To my thinking, table semantics is a must-have, since the only pathway to finding objects to create is via manifest tables. Also table semantics allow filtering (via table indexing) and object creation to be combined in one line which I think is quite nice. 

A question mark for me is whether ID array semantics are actually necessary or desirable for any use cases? (once multi-row tables can be supplied to object constructors). 

There's a note in #102 to show both pathways in the Tutorial(s) with a comment that ID arrays enable easier use of `sortrows`. But I'm no longer sure what I meant since `sortrows` works with tables too.  

I'm not advocating to kill off ID array semantics at this stage. Just drawing attention to it, so we can keep in mind whether it's really necessary. Although flexibility is nice, the fewer pathways to explain and maintain is also a boon. 

Probably the best way for now is to explain both in the EphysTutorial as noted in #102. The process of explanation will force some thought about the "why?".

**Comment by DylanMuir** [comment]
@vijayiyer05 Regarding task 2 about multi-object display, what information would you display for a multi-object array? Suggestion:

```
1x3 OPhysSession array with ids:
 [132342323, 23424132, 124141341]
```

Or what additional information would you include?

**Comment by vijayiyer05** [comment]
@DylanMuir, this was a puzzle I was anticipating, but as I've thought on it recently, I believe likely the "right" answer is to convey some information about the degree of homogeneity and heterogeneity across the `info` struct parameters. 

It could effectively be a computed "collective" info structure, showing values where they pass `isequal` across all array elements and simply showing something like  `<mixed>` where the values differ. 

In the case of `id` it would always be `mixed`; though perhaps one might show the first 2 values and an ellipsis for this special case. 

How sensible and feasible does this idea seem?

**Comment by vijayiyer05** [comment]
@DylanMuir , suggest you proceed with the simple approach you proposed on August 28 for this sprint to help close this out. At the same time, great if you could comment on my proposal from August 29. Capturing our thoughts now will help guide future sprints.

**Comment by DylanMuir** [comment]
@vijayiyer05 Ok, I have a draft implementation in branch `iss_108`

**Comment by vijayiyer05** [comment]
@DylanMuir  Great, this worked for me in moderate testing. I committed some minor refactors/comments to use current style: favor `height` vs `size(x,1)` and to prefer `String`. These appear non-breaking. Ready to proceed to pull request & merge.
