### ISSUE TITLE
Implement download-free mode for cloud installations with local S3 mount

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#109]

**Comment by vijayiyer05** [comment]
One strategy could be to create two modes within `bot.cache.CachedAPICall`

**Comment by brianhu2** [comment]
I have completed a MATLAB script that automates the s3fs mounting process. I have uploaded the script [here](https://mathworks-my.sharepoint.com/:u:/p/brianhu/Ef6IBjL31OdCrCyxJm9oEboB-kVwYhuqm5LK6ec-pY7C4A?e=Shcbkr). To mount the drive:

1. Set up a Linux VM on AWS using the [MATLAB Reference Architecture](https://github.com/mathworks-ref-arch/matlab-on-aws/blob/master/releases/R2021a/README.md).
2. Connect to the VM through RDP (username: ubuntu, password: [password set in step 1 stack creation process].
3. Open MATLAB, log in using MathWorks credentials, and run the script. A new directory called s3-allen should appear with the Allen Institute data mounted.

**Comment by DylanMuir** [comment]
@brianhu2 In branch `iss_109` I made some modifications such that if a file exists on disk in the expected cache location, that file will be used instead of downloading the file from Allen. Code is still needed to place the cache location in the `s3-allen` directory.

**Comment by vijayiyer05** [comment]
@DylanMuir , @brianhu2: 

I've made an untested attempt to manage the cloud file location at 9e84d2deaa4f8cbef7d97ec6f083f9967ac28ee3. This assumes that the the S3 bucket local file storage uses the same "/external" relative paths as are returned from the web API.  

@brianhu2: when you can, please let us know how the folder structure looks on the S3 mount

**Comment by brianhu2** [comment]
@vijayiyer05 @DylanMuir I've taken a few screenshots showing the file structure of the S3 mount. The folders "visual-coding-2p" and "visual-coding-neuropixels" are the top level folders, with the other two screenshots showing the contents of each folder.
![s3-allen filesystem](https://user-images.githubusercontent.com/17368760/133502246-86aa7df2-4d5a-423a-8eaf-33cb07a1772b.png)
![visual-coding-2p contents](https://user-images.githubusercontent.com/17368760/133502252-7580d69e-59f3-4fb0-b829-654b04563de6.png)
![visual-coding-neuropixels contents](https://user-images.githubusercontent.com/17368760/133502257-964047b7-db63-4718-8c6d-07f1dd92f8e5.png)

**Comment by DylanMuir** [comment]
@brianhu2 Could you please give us a shot of the contents of a `session_NNN` folder in ecephys-cache, and inside the corresponding `NNN` folder in raw-data?

**Comment by DylanMuir** [comment]
@brianhu2 Also please the contents of `natural_movie_templates` and `natural_scene_templates`?

**Comment by vijayiyer05** [comment]
Good discussions today @DylanMuir  & @brianhu2 !

Recapping now where I think things stand:

- Within ephys, the scope for the BOT cache should be the `ecephys-cache` folder contents; at the moment, it appears the `raw data` contents are beyond the reach of the web API  (we haven't encountered them yet to my knowledge)
- The web API "folder" hierarchy and the S3 bucket folder hierarchy do **not** match; but the end filenames **mostly** match
  - One near match is the ephys session files. They go by `session_NNN.nwb` in the S3 bucket and `ecephys_session_NNN.nwb` via the web API. 
- If needed, suggest to prioritize ephys to complete issue for this cycle

**Comment by DylanMuir** [comment]
Thoughts for next steps:
* Need to determine whether filenames themselves are *unique* within the S3 bucket hierarchy and also within the web API hierarchy
* Need to determine whether filenames *always match* between web API and S3 bucket
* If both points above are satisfied, then we could implement a filename scanning approach to finding the correct file in the S3 bucket
* If both points are *not* satisfied, then we need to design an approach for automatically matching web API with S3 bucket. Best case would be fully automated, worst case could be a form of look-up table.
