### ISSUE TITLE
Code Reorganization

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#111]
Various updates to code organization

- ~~Move generally useful local helpers (e.g. build_spike_histograam) to bot.util.* package~~
- [x] Move manifest/ophysmanifest/ephysmanifest into bot.item.internal.* package tree; use ItemType enum to streamline if possible

**Comment by DylanMuir** [comment]
Working in branch `iss_111`

**Comment by DylanMuir** [comment]
@vijayiyer05 Ok, I think this is working. Please merge the other branches and I will re-test this branch.

**Comment by vijayiyer05** [comment]
@DylanMuir  This looks good by inspection from my end. I've also struck task 1, since the one local function in mind (`zlclBuildSpikeHistogram`) probably isn't ready/meant to be a general utility at this time.

**Comment by vijayiyer05** [comment]
@DylanMuir  Commenting what you probably already realized: this issue should be the last of the Review set to merge, after re-test.
