### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#112]
Various refactoring updates

- [x] Avoid/replace usage of bsxfun with implicit array expansion where possible
- [x] The function bot.internal.manifest2item can likely be retired, as most functionality could be folded into manifest class implementations

**Comment by DylanMuir** [comment]
@vijayiyer05 Please review branch `iss112`

**Comment by vijayiyer05** [comment]
@DylanMuir : looks good to me. 

Looks like this was forked off the branch `frontend`? 

Since the work of Ethan & Kevin is done, I suggest we could first merge frontend into `master` and then your work (including merging this issue) could be done off master. Make sense?

**Comment by DylanMuir** [comment]
@vijayiyer05 I merged `master` into this branch; it's ready to be merged into `master` now. Please review and merge.

**Comment by vijayiyer05** [comment]
Merged via cherry-pick at 9d00ca4
