### ISSUE TITLE
Physiology Demo Updates

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#114]
The physiology demos intend to show the "why" of the dataset and tool, by illustrating representative scientific analysis. 

Work on this issue should try to remove extensive didactic language from the demo scripts, replacing by reference to the tutorial.

**Comment by kzhou085** [comment]
I've completed drafts of the updated ephys and ophys demos and placed them under the frontend branch, so feedback and a review on those would be appreciated! Thanks!

**Comment by vijayiyer05** [comment]
I've had a chance to look over the updated EphysDemo. It's considerably tightened which is great! 

This tightening helped me to better think about how the overall story could flow better, which I've captured in the attached document: [EphysDemoNotes.docx](https://github.com/emeyers/Brain-Observatory-Toolbox/files/6835413/EphysDemoNotes.docx).

The overall idea is to remove the bias towards Item hierarchy ordering (Session --> Probe --> Channel --> Unit). This likely makes sense for the Tutorial, but here was just causing the narrative to be disjointed. 

The suggested new organization jumps right to Units and then follows the experimental [session order](https://allensdk.readthedocs.io/en/latest/_static/neuropixels_stimulus_sets.png): first the Gabor patches for receptive field mapping as a control and then the static gratings for an orientation tuning curve. The LFPs are saved for last as mostly a bonus topic. 

This is mostly a reordering that should be straightforward. The [document](https://github.com/emeyers/Brain-Observatory-Toolbox/files/6835413/EphysDemoNotes.docx) also adds some suggestions for each sub-section, for small things to add and how to make transitions between sections.

**Comment by vijayiyer05** [comment]
@kzhou085 : added this Issue as an explicit assignment because I _think_ that will ensure you get notifications all the comments

**Comment by vijayiyer05** [comment]
Note the new [suggested outline](https://github.com/emeyers/Brain-Observatory-Toolbox/files/6835413/EphysDemoNotes.docx) removes the pupil location section. I may be missing something, but it seems unneeded for the story. My suggestion is to peel that off over to the new behavior tutorial (#110).

**Comment by vijayiyer05** [comment]
For the section currently titled "Accessing linked items: firing rates across brain regions", it's possible to:

- [ ] use the existing "ephys_structure_acronyms" Session property that already implements the strip(split(...))
- [ ] completely remove the use of cell arrays and simply use [tabular indexing](https://www.mathworks.com/help/matlab/matlab_prog/access-data-in-a-table.html) to get the firing rates for cortical vs subcortical

This reduces things down to 2 lines of code before the histogram calls

I've figured it out but for now have left it as an exercise for the reader ;-)

**Comment by kzhou085** [comment]
Great, I've looked at the document and made the corresponding changes. Another round of review would be appreciated!

**Comment by vijayiyer05** [comment]
@kzhou085 :   I think the `EphysDemo.mlx` is shaping up nicely!

I've captured some further suggested refinements as PDF markup: [EphysDemo.pdf](https://github.com/emeyers/Brain-Observatory-Toolbox/files/6874327/EphysDemo.pdf). 

Note that for the comment above, it doesn't seem like the first checked item was done, i.e. use the existing Session property (`structure_acronyms`) rather than re-implementing the `strip(split(...))` logic.  

Note this could be a good simple example for the Tutorial to show what the "Info Derived Values" property group means, i.e. values computed from data contained within the `info` property. But for the demo, I would stick to the scientific narrative and simply use the existing property with limited explanation.

**Comment by vijayiyer05** [comment]
These tutorials were included (with my edits) in [Release v0.9.2](https://github.com/emeyers/Brain-Observatory-Toolbox/releases/tag/v0.9.2)
