### ISSUE TITLE
error using bot.util.StimulusAlignedResp

### ISSUE THREAD

**Issue by Xinzhu-Fang** [emeyers/Brain-Observatory-Toolbox#12]
![image](https://user-images.githubusercontent.com/29473163/36706586-881486fe-1b38-11e8-8851-244ef93d5fc6.png)
Hi Dylan, 
I got an error as shown above. Basically, `tStimulus` is yelled at for not having the `frame` column. Besides, I wonder what you mean by "overlapping fluorescence frames".
Thanks
Cindy

**Comment by DylanMuir** [comment]
Hi @Xinzhu-Fang, please pull the latest commit and try now. The `frame` column was anyway unused in the function, and so was incorrectly required.

**Comment by DylanMuir** [comment]
The comment about "overlapping fluorescence frames" was poorly worded. Some stimulus switches occur mid-fluorescence frame, with the result that those fluorescence frames are "dirty" — they cannot be assigned to one or another stimulus frame. Those fluorescence frames are discarded.

**Comment by Xinzhu-Fang** [comment]
![image](https://user-images.githubusercontent.com/29473163/36759643-163b04dc-1be6-11e8-824f-87292f082756.png)

**Comment by DylanMuir** [comment]
Weird that this isn't working for drifting grating stimuli. I'll take another look.

**Comment by DylanMuir** [comment]
Sorry @Xinzhu-Fang, I can't reproduce this. Could you please let me know what the session ID is for the session you are trying?

````
>> bos = bot.session(527745328)

bos = 

  session with properties:

               sSessionInfo: [1×1 struct]
    strLocalNWBFileLocation: '/Users/dylan/Development/Brain-Observatory-Toolbox_GIT/+bot/Cache/external/neuralcoding/prod12/specimen_517650091/ophys_experiment_527745328/527745328.nwb'

>> bos = bot.session(527745328);
>> tStimDG = bos.get_stimulus_table('drifting_gratings');
>> [vtTime, mfResp] = bos.get_fluorescence_traces();
>> mfAlignedResp = bot.util.StimulusAlignedResp(tStimDG, mfResp);
>> whos mfAlignedResp
  Name                 Size              Bytes  Class     Attributes

  mfAlignedResp      628x254            638048  single              
````

**Comment by DylanMuir** [comment]
Also, I don't think this will work with raster-converted data, since the trial-averaging has already occurred. This function is designed to work with the raw fluorescence responses.

**Comment by Xinzhu-Fang** [comment]
yes, raster data are already epoched for each stimulus. I think it was the mismatch between time length caused that error.
