### ISSUE TITLE
Provide estimated progress display updates during long downloads

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#124]
Per suggestion of Artemio Soto Breceda on [File Exchange](https://www.mathworks.com/matlabcentral/fileexchange/90900-brain-observatory-toolbox).

**Comment by ehennestad** [comment]
This issue resulted in a [FEX contribution](https://se.mathworks.com/matlabcentral/fileexchange/118460-file-download-with-progress-monitor) which was added to the BOT toolbox in commit c62559e157db2f5aff93945163e51914cf2ccc1a
