### ISSUE TITLE
Front-end support v0.9.3

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#125]
Umbrella Issue to track time/conversations related to technical support of the front-end team during v0.9.3 work.

**Comment by kzhou085** [comment]
Running the Ephys Demo gives me an error under the "Accessing probe-centric data" section: 

Error using h5readc
The filename specified was either not found on the MATLAB path or it contains unsupported characters.Error in h5read (line 93)
[data,var_class] = h5readc(Filename,Dataset,start,count,stride);Error in bot.item.ephysprobe/zprpGetCSD (line 116)
 csd = h5read(nwbLocalFile, ...Error in bot.item.ephysprobe/get.csdData (line 77)
 self.property_cache.vertical_position] = self.zprpGetCSD();

This error seems to be occurring every time I run the demo.

Thanks!

**Comment by DylanMuir** [comment]
@kzhou085 I couldn't manage to reproduce the error, unfortunately. Maybe try clearing your cache completely by moving or renaming the `+bot/Cache` directory, and run the demo again from scratch?

**Comment by kzhou085** [comment]
Clearing my cache worked, thanks!
