### ISSUE TITLE
Error Vijay had using the BOT

### ISSUE THREAD

**Issue by emeyers** [emeyers/Brain-Observatory-Toolbox#13]
Below is an error Vijay had using the BOT. If anyone knows what is causing this that would be useful (I will try to look into it too)...  

From Vijay:

I was trying to use the BOT to access a different session with more running, but  then I started running into issues with the BOT. I keep getting error messages like what I list below. I actually get this now if I just re-run the unmodified example script.

Have you seen this error before? Are BOT downloads are currently working for you? I’m trying to figure out if perhaps things are currently down from the Allen side; or if there’s something on the BOT or my side causing these errors.

Vijay

 

Error using bot.cache/CacheFilesForSessionIDs (line 196)
The NWB file for a session ID [501729039] could not be cached.

 Error in bot.session/EnsureCached (line 193)
         strCacheFile = bos.bocCache.CacheFilesForSessionIDs(bos.sSessionInfo.id);

Error in bot.session/get_cell_specimen_ids (line 313)
         EnsureCached(bos);

Caused by:
    Error using bot.internal.CloudCacher/websave (line 107)
    Could not access URL.
  
      Error using websave (line 107)
The error "Error copying data." occurred while communicating with URL 'http://api.brain-map.org/api/v2/well_known_file_download/516804316'.

**Comment by Xinzhu-Fang** [comment]
I just cached the nwb file for this session. I would say it was that for a moment either the Allen server was down or Vijay's internet was down, not a BOT issue. Please ask him to try again.

**Comment by Xinzhu-Fang** [comment]
guess confirmed by Vijay.
