### ISSUE TITLE
Unexpected behavior when creating a Unit object and ophys manifest is missing

### ISSUE THREAD

**Issue by ehennestad** [emeyers/Brain-Observatory-Toolbox#146]
I am creating a Unit object from an ephys session, but I did not expect the resulting output:

```
>> ephysSessionTable = bot.fetchSessions('ephys');
>> ephysSession5 = bot.session( ephysSessionTable(5,:) );
>> session5Units = ephysSession5.units;
>> unit1 = bot.unit( session5Units(1,:) )
Fetching OPhys manifests...
```
This might be inconvenient to those who are only interested in the ephys data.

The problem arises on the following line in the `bot.item.Unit` constructor:

https://github.com/emeyers/Brain-Observatory-Toolbox/blob/d6e2f3c4c97eb215062e2c781a7e88fa032e90d5/%2Bbot/%2Bitem/Unit.m#L66

When calling bot.session, internally there is a try/catch block where an attempt is made to create an ophys session, and if that fails an ephys session is created instead:

https://github.com/emeyers/Brain-Observatory-Toolbox/blob/d6e2f3c4c97eb215062e2c781a7e88fa032e90d5/%2Bbot/session.m#L43-L53

Are there any arguments against either calling :

`obj.session = bot.item.concrete.EphysSession(obj.info.ephys_session_id)` 

or maybe better :

`obj.session = bot.session(obj.info.ephys_session_id, "ephys")` 

in the `bot.item.Unit` constructor?

**Comment by stevevanhooser** [comment]
Hearing no objections, I'll go ahead and close the issue (anyone is welcome to request a re-open)

**Comment by ehennestad** [comment]
Thanks Steve.

I had already added to proposed change, but forgot to close the issue!
