### ISSUE TITLE
Allow user-specified cache location

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#149]
The BOT folder may not be the ideal location for the cache in all cases

**Comment by vijayiyer05** [comment]
@ehennestad Marking this as in progress since I can see it's at least partly implemented. 

By inspection, here is one suggestion : make the default a subfolder of `userpath` called "Brain Observatory Toolbox Cache"

This should handle two use cases smoothly:
- Installation of BOT by Add-on Explorer (i.e. where BOT package is available but not shown as a folder user is working in)
- Running on MATLAB Online (where the `userpath` will be MATLAB Drive)

-- (this would work both for con shFor installation by Add-on Ex
- For installation by Add-on Explorer, it's esse

**Comment by ehennestad** [comment]
Nice, I did not know about `userpath`, but this is a good solution for the default path. One thing should be considered: if someone would update the toolbox, and they already have a cache directory that resides in the toolbox itself. 

Maybe a test for whether .../+bot/Cache folder already exists, and if not, set the default as you suggest above.

**Comment by vijayiyer05** [comment]
Small detail came up. After specifying the cache folder (or accepting the default location), if you delete the cache folder, then on a subsequent run you will get an error the folder doesn't exist. A preferred behavior would be to re-create the cache folder, possibly with a warning message.

**Comment by ehennestad** [comment]
Add a dialog where user can select to recreate the cache directory if it does not exist

**Comment by ehennestad** [comment]
Added commit c411305 for previous point
