### ISSUE TITLE
Download item tables (manifests) from s3 instead of API

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#150]

**Comment by vijayiyer05** [comment]
@ehennestad I was able to verify this on MATLAB Online. Very nice! 

Strangely I'm not able to get it working on my laptop. I set the preference to 'S3' and then try accessing an uncached item, and get the message shown below

Any quick ideas? 

![image](https://user-images.githubusercontent.com/23032671/196060318-d33d1475-f776-4496-8089-950cb7bde3d8.png)

**Comment by ehennestad** [comment]
This should be addressed in the above commit. The download url was joined using fullfile, resulting in the wrong kind of slash for urls.

**Comment by ehennestad** [comment]
Note: The above comments are related to issue #109

**Comment by vijayiyer05** [comment]
Over the weekend, I will:
- [ ] Test again how S3 vs REST affects manifest retrieval times

At the moment, `fetchSessions` remains a time-consuming call on the first run during a new session. 

@ehennestad, I believe we discussed the idea of possibly caching the manifest, right? If so, does that still seem like a possibly good idea? If so, we should capture it as an issue for a future version.
