### ISSUE TITLE
Enable S3 protocol retrieval for Item object/property access

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#153]
Issue capturing opportunistic performance enhancement that arose from supporting download-free mode (#109 )

**Comment by vijayiyer05** [comment]
Transferred from #150

> @ehennestad I was able to verify this on MATLAB Online. Very nice!
> 
> Strangely I'm not able to get it working on my laptop. I set the preference to 'S3' and then try accessing an uncached item, and get the message shown below
> 
> Any quick ideas?
> 
> ![image](https://user-images.githubusercontent.com/23032671/196060318-d33d1475-f776-4496-8089-950cb7bde3d8.png)

**Comment by vijayiyer05** [comment]
Per @ehennestad (from #150):

f614be56e2858389fb61e6943884d61f4099e914

> This should be addressed in the above commit.  The download url was joined using fullfile, resulting in the wrong kind of slash for urls on a machine running windows

**Comment by vijayiyer05** [comment]
@ehennestad Confirmed that it works on a local Windows machine now. 

On my first try, however, creating new item objects (Ephys session objects) was ~10% faster with API access than S3 item.  Small enough difference that it could well be random bandwidth fluctuations. 

Though I'm also wondering: how much row to row variation is there for the retrieval size to construct a session object?

**Comment by ehennestad** [comment]
![image](https://user-images.githubusercontent.com/17237719/196461975-3cc03f88-f361-4a0d-968f-3ba6af21b801.png)

Example of file size for sessions 1-12. There is some variation there.
