### ISSUE TITLE
no access to stimulus info

### ISSUE THREAD

**Issue by el070420** [emeyers/Brain-Observatory-Toolbox#155]
when trying to access stimulus names or epochs, I get this error:

Unrecognized method, property, or field 'stimulus_block' for class
'bot.item.internal.enum.OnDemandState'.

Error in bot.item.concrete.EphysSession/getStimulusEpochsByDuration (line 435)
            diff_indices = zlclDiffIntervals(presentations.stimulus_block);

Error in bot.item.concrete.EphysSession/get.stimulus_epochs (line 262)
            epochs = self.getStimulusEpochsByDuration();

**Comment by ehennestad** [comment]
Did you experience this for multiple sessions? In any case, it would be useful to know which sessions you get this error for

**Comment by ehennestad** [comment]
It seems like this is an error that might happen for a subset of sessions. I have added a fix in the dev branch (will be released in late December/early January). If this still is of interest to you, you could test it there, and let us know if that fixes the issue!

**Comment by vijayiyer05** [comment]
@el070420 If you are so inclined, you could try the dev branch where this issue appears fixed. Otherwise, it will be included in the v0.9.3 release coming soon!

**Comment by vijayiyer05** [comment]
@el070420 FYI, the v0.9.3 release has gone out. Any input you may have on this issue for the latest release is welcomed.

**Comment by Chockalingam31** [comment]
@vijayiyer05 Hi! I am trying to download session id: 768515987, but having the same error..could you please let me know if there is a way around it? Thanks!

**Comment by stevevanhooser** [comment]
This issue appears to be resolved. @el070420 please request a re-open if you are still having problems.
Best
Steve
