### ISSUE TITLE
Restore end-to-end OphysDemo with suitable example ophys session

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#40]
Current OphysDemo example uses the filters:
* Structure=VISp
* Depth=275
* Session Type = A (drifting grating + natural movies)
* Cre Line = 'Emx1-IRES-Cre'

As of this date, a [web query](http://observatory.brain-map.org/visualcoding/search/overview?area=VISp&imaging_depth=275&tld1_name=Emx1-IRES-Cre&sort_field=tld1_name&sort_dir=asc) returns 3 experiments, none of which have eye tracking data for Session A. 

This leads to a failure to pass the "fail_eye_tracking"=false filter. Thus no sessions are returned & the demo fails early.

**Comment by vijayiyer05** [comment]
There are some sessions (e.g. 501574836 & 501836392) where fail_eye_tracking = false but there is no eye tracking data in the associated NWB file. 

For these sessions, a web query of the parent experiment containers ([511510667](https://observatory.brain-map.org/visualcoding/search/experiment?id=511510667) & [511510650](https://observatory.brain-map.org/visualcoding/search/experiment?id=511510650) respectively) shows only a thumbnail icon for the Eye Position data rather than actual data. 

These "false eye tracking success" sessions are distinguishable from the "true eye tracking failures" which report fail_eye_tracking=true via the API and display NA on the web query.

To identify a proper session for a restored ophys demo, these "false eye tracking success" sessions will need to be avoided.

**Comment by DylanMuir** [comment]
@vijayiyer05 I hand-chose a session which at least works and has valid eye tracking data.

**Comment by vijayiyer05** [comment]
Thanks @DylanMuir for finding this. That [experiment](https://observatory.brain-map.org/visualcoding/search/experiment?id=511510695) does look like it should/did work. For some reason I get an error on the call to `session`. 

Reopening issue as a placeholder for now. This may be some repo state difference. When finished with merges of #36 and #37  (I sent over a few small proposed fixes on latter), I will try again and update.

**Comment by vijayiyer05** [comment]
The updated script runs end-to-end now on my end as well after rebuilding cache. 

Opening issue to keep open the sub-tasks (assigned to @vijayiyer05): 

- [ ] Update narrative to match new experiment/session selections 
- [ ] Update filtering steps (via table operations) to match new experiment/session selections

@DylanMuir: if anything comes to mind (off the top of your head) that would be helpful for the narrative with this new selection, please comment here or DM me. Thanks again for identifying a suitable session.

**Comment by vijayiyer05** [comment]
@DylanMuir  FYI, completed updates to OphysDemo narrative/filtering to match the session you found. We're getting there.
