### ISSUE TITLE
Production of a GitHub release (v0.9)

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#42]
- [x] stable working version of the Project incorporating all project improvements
- [x] up-to-date descriptive README file suitable for a new MATLAB end user to install and begin to use the Project.
- [x] Update README with links to rendered demo MLX files

**Comment by vijayiyer05** [comment]
Considering that the release is proximal in time to R2021a release, the following may be a sensible approach:

1. Release "v1.0-beta" tied to R2020b, for this project on our original timeline (ideally by Coysne 2021)
2. Release "v1.0" soon thereafter tied to R2021a, soon thereafter 

Have set up new [project](https://github.com/emeyers/Brain-Observatory-Toolbox/projects/7) with the concept/items for this second release (assigned to @vijayiyer05) .

**Comment by vijayiyer05** [comment]
Additional suggested item:
- [ ] Uniform look & feel for doc strings of the top-level bot functions. Aim that `help bot` shows a consistent description across the table fetch and object creation functions.

Suggest issue owner maintains first comment (editable) as "the" list for this Issue.
