### ISSUE TITLE
Implement properties repeated across the item object hierarchy where applicable 

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#48]
Example: 
Currently accessing experimental data is via the `bot.internal.ephyssession` class, which reads data in bulk from the NWB files. `unit` and `channel` could sensibly have corresponding methods to access waveforms, spike times, LFP, CSD, etc.

**Comment by vijayiyer05** [comment]
Merged into issue #76
