### ISSUE TITLE
Item Object Design

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#54]
Issue converted from note from @vijayiyer05 

- [ ] Consider whether "metadata" is the best property name to describe the web-available tabular data accessed via API.  Rename if better alternative emerges.
- [ ] Remove property implementations that are redundant with the "metadata" structure fields, e.g. age, genotype, # probes, etc.

**Comment by vijayiyer05** [comment]
Moved these items into issue #57 ; all related to the item object interface
