### ISSUE TITLE
Folder organization

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#55]
Issue converted from note from @vijayiyer05 

- [x] Move +nwb to become an +internal subpackage
- [x] Move +internal classes linked to items (sessions, experiments, units, probes, etc) to a new +items package. 
- [x] Move `bot.test` to +internal

**Comment by vijayiyer05** [comment]
Meant for +items to be exposed, i.e. bot.items.*, rather than within bot.internal.*. 

Implemented this update at a94762b83a547ab1344009c5db59f2c0edd57a21.

Looks good.
