### ISSUE TITLE
Item Object Interface

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#57]
Issue converted from note from @vijayiyer05 

- [x] 1. Hide internal methods for item objects, e.g. cache & nwb methods, including constructor methods
- [x] 2. Consider whether "metadata" is the best property name to describe the web-available tabular data accessed via API. Rename if better alternative emerges.
- [x]  3. Remove property implementations that are redundant with the "metadata" structure fields, e.g. age, genotype, # probes, etc.
- [x] Represent item table UserData properties as ItemObject core properties
- [x] Convert as many methods as possible into properties, for a consistent interface

**Comment by vijayiyer05** [comment]
Ongoing work in backend branch: https://github.com/emeyers/Brain-Observatory-Toolbox/tree/backend

**Comment by vijayiyer05** [comment]
Completed original punchlist on as of 37acc8e

**Comment by vijayiyer05** [comment]
Additional items:

- [ ]  Represent item table UserData properties as ItemObject core properties
