### ISSUE TITLE
Item Object Implementation

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#59]
Issue converted from note from @vijayiyer05 

- [x] Implement array construction of Item objects

- [ ] #129

**Comment by vijayiyer05** [comment]
@DylanMuir, it appears as if you started work on this issue's first task, i.e. the array construction case? 

As I look at this issue again, it seems the first task should be part of #108 and the second item could probably be deferred. 

Array objects are a timely issues, as it relates to ongoing work this summer on #116.

**Comment by DylanMuir** [comment]
Yes, I didn't spot the duplication. Array construction is now implemented I believe.

**Comment by vijayiyer05** [comment]
Closing this as a duplicate. Converting second task to a new Issue (deferred).
