### ISSUE TITLE
HDF5 commands on windows require opposite slash than returned by `filesep`

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#6]
This implies that the hdf5 reading commands fail on windows

**Comment by DylanMuir** [comment]
Hi @Xinzhu-Fang, I have push some edits to `bot.session` that should hopefully resolve the issue on Windows: [371d825](https://github.com/emeyers/Brain-Observatory-Toolbox/commit/371d825a06eb2d6b98a262c36239103c958adcde).

Could you please pull these changes and check?

**Comment by Xinzhu-Fang** [comment]
My matlab license on my laptop expired last week. I cannot get a new one until next week.

**Comment by DylanMuir** [comment]
Hi Cindy, any movement on the matlab license? Please let me know if there are more edits needed.

**Comment by Xinzhu-Fang** [comment]
Hi Dylan, the school started today so I am busy figuring out classes. I am planning to work on that and to update you on Wed. Let me know if you cannot wait that long.

**Comment by DylanMuir** [comment]
Wednesday is fine, of course.

**Comment by Xinzhu-Fang** [comment]
I am still getting the same errors. I think it's because not all the `fullfile` functions inside `h5read` functions have been replaced by your `h5path` functions in `session.m`. Here is an example:

![image](https://user-images.githubusercontent.com/29473163/35369300-59336aaa-0155-11e8-9179-8192bbdae767.png)

**Comment by DylanMuir** [comment]
I thought I replaced all of those. Ok, I've pushed another commit, please try again.

**Comment by Xinzhu-Fang** [comment]
good now

**Comment by emeyers** [comment]
Great, shall we go ahead and merge the changes?

Ethan

**Comment by DylanMuir** [comment]
Good to go. I'll make another pull tequest afterwards, for the parallel downloading code.
