### ISSUE TITLE
Ephys Demo Elaboration & Streamlining

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#60]
- [ ] Enrich the Neuro story
- [ ] Migrate the technical "how" elements towards the QuickStart

**Comment by vijayiyer05** [comment]
Capturing ideas to enrich the Neuro story in EphysDemo:
* Distribution of OSI across the recorded regions
* Summary of brain regions in current dataset, w/ relation to whole dataset

**Comment by ShuboChakrabarti** [comment]
- Enriched the neuro story significantly with several additional analyses - firing rate across brain regions, RF etc
- added a schematic to clarify the organization of different linked dataset item types
- added two examples with explanation of using conditionwise() and presentationwise() methods to query stimulus related responses
- added more links to Allen Institute docs for clarity
