### ISSUE TITLE
Unify and Elaborate Lowest-Level Item Implementations

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#62]
The lowest-level items in the dataset API (units for ephys, cells for ophys) are the result of the data resource's processing pipeline and contain much information of value for scientific end users.

- [x] Consider creation of Cell item as the lowest-level item for Ophys analagous to Unit for Ephys. Possible internal unification with an abstract internal superclass. 
- [x] Explore the implementation of methods or other means to download and return tables of metrics made available by the data resource for lowest-level items: precomputed metrics for [cells](https://allensdk.readthedocs.io/en/latest/brain_observatory.html) and quality metrics for [units](https://allensdk.readthedocs.io/en/latest/visual_coding_neuropixels.html)

**Comment by DylanMuir** [comment]
@vijayiyer05 Please review.

`units = bot.fetchUnits()` returns metrics with the units table.
`cells = bot.fetchCells()` returns a table of OPhys cells from the OPhys manifest, containing metrics for each cell.

`c = bot.cell(id)` constructs a `Cell` object, analogous to other `Item`s.

**Comment by vijayiyer05** [comment]
@DylanMuir: I'm quite excited about this one! I believe these bring us much closer to core feature completeness. 

I confirmed running all three. Nice.

A few comments/ideas:

- Seeing how long the `.info` properties currently are, I suggest to add a separate `.metrics` property to the `Unit` and `Cell` objects to represent those in separate structures
- Seeing how wide the tables get with combined info & metrics, I suggest adding an `includeMetrics` argument to these fetch functions, with a default value of `false`.
- Many of the Cell info columns are filenames, making it very long. Suggest to add a rule to `applyUserDisplayLogic` which truncates detected filename strings to something very short so they don't eat up any space. 
- I'm surprised at the number of cell array variables for the cells table (including the various filenames). I thought `applyUserDisplayLogic` was converting more of these to strings. Haven't had a chance to investigate more closely. 
- If it's trivial, it _might_ also be sensible to preemptively add `fetchUnitMetrics` and `fetchCellMetrics` functions which grab metrics alone. These should include some minimal info (including id) and support object creation via these tables. We may discover use cases of filtering mostly/fully by metrics via these more focused tables. 

I haven't evaluated too closely the feasiblity of each. If some seem like low-hanging fruit, you might want to grab them now.

**Comment by DylanMuir** [comment]
@vijayiyer05 I will look at 1 and 2; I suggest promoting 3–5 to issues in their own right for later improvement.

**Comment by DylanMuir** [comment]
Problem: I made a `mixin` to handle defining and moving metrics to a separate structure. But this needs to modify the `info` structure, which was defined with `SetAccess = protected`. I needed to make `SetAccess = public` in order to modify that property, which is not ideal.

Otherwise `fetchCells` and `fetchUnits` now optionally includes or excludes metrics. `Cell` and `Unit` objects have a `metrics` property; the contents are defined in the `Cell` and `Unit` classes.

@vijayiyer05 please review and merge.

**Comment by vijayiyer05** [comment]
@DylanMuir : 

Results look good!

In terms of implementation, I can see a few options that I think are better than blanket access for the `info` property (as well as the `CORE_PROPERTIES` and `LINKED_ITEM_PROPERTIES` properties): 

1. Making this a "MetricsItem" class than inherits from `Item`. Currently there isn't a class that would inherit from both `LinkedFilesItem` and `MetricsItem`, so there isn't strictly a need for a mixin (i.e. multiple inheritance)
2. Using an [access control list](https://www.mathworks.com/help/matlab/matlab_oop/selective-access-to-class-methods.html) to specify which mixin(s) have access. This list can grow as the need arises. 
3. Combining 1&2 to create a `MixinItem` abstract class of which `LinkedFilesItem` and `MetricsItem` would be subclasses; and then Item would give access just to `MixinItem`

I was about to start one of these and just go with it, but I wonder if you have a preference?

**Comment by DylanMuir** [comment]
@vijayiyer05 My preference would be option 2 rather than making the class hierarchy deeper, but I see your point about no technical need for a mixin.

**Comment by vijayiyer05** [comment]
@DylanMuir sounds good!

**Comment by vijayiyer05** [comment]
@DylanMuir  I was about to implement this. But then I see option 2 doesn't quite work cleanly b/c we want to grant access to children and specific mixins, which seems messy. 

I've created #135 to take this up later. 

Let's leave it as is. I'm creating a pull request.

**Comment by vijayiyer05** [comment]
PR #136  documents this merge.
