### ISSUE TITLE
Item Tables

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#63]
Issue converted from note from @vijayiyer05 

- [x] Present structure acronyms (e.g. "VISlm") vs structure ids across public API, i.e. in table values. 
- [x] Convert ephys_structure_acronyms variable values to string arrays for can be a string cell array, for easier use and better table display. (Implementation along the lines of:
`availSessions.ephys_structure_acronyms = cellfun(@(x)string(x(1:end-1)'),availSessions.ephys_structure_acronyms,'UniformOutput',false)`)
- [x] Make editorial decisions on order of columns in table, e.g. moving less scientifically interesting vars, all equal vars (e.g. has_nwb), or undisplayable vars (struct vars etc) to end. Can implement using `movevars()`
- [x] Consider moving all-equal vars, e.g. 'Ephys' and 'has_nwb' as table custom properties versus table vars, i.e. reducing column count.

**Comment by vijayiyer05** [comment]
Work underway on backend branch: https://github.com/emeyers/Brain-Observatory-Toolbox/tree/backend
