### ISSUE TITLE
Ephys_Demo: session.stimulus_names query crash

### ISSUE THREAD

**Issue by ShuboChakrabarti** [emeyers/Brain-Observatory-Toolbox#90]
Calling the session.stimulus_names property causes crash for particular sessions (selecting sessions 3 onwards on Line 13)

**Comment by ehennestad** [comment]
This seem to be the same problem that was adressed in issue #155

**Comment by stevevanhooser** [comment]
Closing under the assumption that it is addressed in #155. @ShuboChakrabarti you are welcome to request a re-open.
