### ISSUE TITLE
Consider fluorescence_traces_dff timestamp handling

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#92]
Ophys session properties are now uniformly accessed as a single value output. 

Since the found implementation of the fluorescence_traces_dff property was explicitly determining both the timestamps and the traces (via two separate h5 reads), these are packed into a compound structure type. This requires the end user to unpack. 

@dylanmuir: Is there a reason you can recall why fluorescence_traces_dff explicitly reads its H5 timestamps rather than simply re-using the fluorescence_timestamps vector as done with the other fluorescence_traces properties (e.g. demixed)? Or better put: do you expect the DFF timestamps could ever differ from the fluorescence timestamps. So far the dff timestamps and original fluorescence timestamps always seem identical. If we always expect this, we could simplify the user interface (while adding a check/confirmation if it seems wise).

**Comment by DylanMuir** [comment]
I can't recall an explicit reason, and it would be surprising for the DFF timestamps to differ from the other fluorescence signal timestamps.

**Comment by vijayiyer05** [comment]
Now part of #95
