### ISSUE TITLE
rename master to main or similar

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#96]
Black lives matter

**Comment by vijayiyer05** [comment]
Hi @emeyers, they've made it easy to update to a better name (say "main") for our default branch (instead of "master"). 

Can you give [this](https://github.com/github/renaming) a try?

**Comment by emeyers** [comment]
Just updated the default branch from master to main. To update local clones
use:

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
