### ISSUE TITLE
Restore lightweight stimulus presentation "aspect" properties (if possible)

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#97]
The `.stimulus_names`, `stimulus_epochs`, etc "aspect" properties now simply access the full `stimulus_presentations` table. This is somewhat heavyweight & defeats the purpose of having the lightweight aspect properties. 

There also used to be a lightweight aspect property for the number of presentations (`ephys num_stimulus_presentations`), which is currently defunct since it also requires full access to `.stimulus_presentations`. 

if there's a fast way to get at size & other aspects without full access, these properties can be kept/reviived. The number could even be used to give a hint on the size of `.stimulus_presentations` before access

If this is not possible, these properties should likely be removed

**Comment by vijayiyer05** [comment]
Given the speedups brought about by S3 & download-free, suggest to leave as is & close out this issue, pending just the following fix:

- Fix issue where `stimulus_name` & `stimulus_epoch` still show as <On Demand> after being accessed

**Comment by ehennestad** [comment]
Made some updates here:
num_stimulus_presentations and stimulus_names are now retrieved in a lightweight manner. 
stimulus_names and stimulus_epochs are now shown properly after being accessed.

As far as I can see, to get stimulus_epochs, the whole stimulus presentation table has to be accessed, so I leave retrieval of that one as is, and suggest that this issue can be closed

**Comment by ehennestad** [comment]
Note also that the performance for retrieving the stimulus_presentations table was significantly improved with commit a3cd102
